import { decodeHTMLEntities } from 'utils/decodeHtml'
import { getFaviconURI } from 'utils/getFaviconURI'
import { FEEDLY_TOKEN } from 'utils/secrets'

export const getFeedlyFeed = async (url: string) => {
  const data = await fetch(
    `https://api.feedly.com/v3/search/feeds?${new URLSearchParams({
      q: url!,
      n: '8',
      withWebsite: 'true',
      autocomplete: 'true',
      fullTerm: 'false',
      locale: 'en',
      ct: 'feedly.desktop',
      // cv: `31.0.2046`,
      ck: `${Date.now()}`,
    })}`,
    {
      headers: {
        Authorization: `Bearer ${FEEDLY_TOKEN}`,
        'Content-Type': 'application/json',
        'User-Agent': `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`,
        Origin: `https://feedly.com`,
        Referer: `https://feedly.com/`,
      },
    },
  ).then<R>((r) => r.json())

  const result = data.results?.[0]

  if (!result) {
    return {
      url,
    }
  }

  return {
    url,
    xmlURL: result.feedId.replace('feed/', ''),
    htmlURL: result.website ?? url,
    title: result.title
      ? decodeHTMLEntities(result.title)
      : new URL(url).hostname,
    description: result.description,
    favicon: await getFaviconURI(url!),
  }
}

// Generated by https://quicktype.io

export interface R {
  success: boolean
  results: Result[]
}

export interface Result {
  scheme: string
  lastUpdated: number
  score: number
  coverUrl: string
  description: string
  language: string
  id: string
  title: string
  feedId: string
  website: string
  topics: string[]
  subscribers: number
  velocity: number
  updated: number
  iconUrl: string
  visualUrl: string
  partial: boolean
}
