import { DISCORD_APPLICATION_ID } from 'utils/env'
import { env } from 'utils/secrets'

export const getWebhooks = async (guild_id: string): Promise<Webhook[]> => {
  const data = await fetch(
    `https://discord.com/api/v10/guilds/${guild_id}/webhooks`,
    {
      headers: { Authorization: `Bot ${env().DISCORD_BOT_TOKEN}` },
    },
  ).then<Webhook[]>((r) => r.json())

  return data.filter((w) => w.application_id === DISCORD_APPLICATION_ID)
}

// Generated by https://quicktype.io

export interface Webhook {
  application_id: string | null
  avatar: string | null
  channel_id: string
  guild_id: string
  id: string
  name: string
  type: number
  user: User
  token: string
  url: string
}

export interface User {
  id: string
  username: string
  avatar: string
  discriminator: string
  public_flags: number
  premium_type: number
  flags: number
  banner: string | null
  accent_color: string | null
  global_name: string
  avatar_decoration_data: string | null
  banner_color: string | null
}
