import { zValidator } from '@hono/zod-validator'
import { Hono } from 'hono'
import { z } from 'zod'

export const rss2json = new Hono().get(
  `/rss2json`,
  zValidator('query', z.object({ xmlURL: z.string() })),
  async (c) => {
    const param = c.req.valid('query')
    const xmlURL = param.xmlURL

    const json = await fetch(`https://rss2json.deno.dev/${xmlURL}`).then<R>(
      (r) => r.json(),
    )

    return c.json(json)
  },
)

// Generated by https://quicktype.io

export interface R {
  result: Result[]
}

export interface Result {
  id: string
  updated: string
  updatedRaw: string
  title: Content
  links: Link[]
  attachments: any[]
  content: Content
}

export interface Content {
  value: string
  type: Type
}

export enum Type {
  HTML = 'html',
}

export interface Link {
  href: string
}
