import Parser from 'rss-parser'

const parser = new Parser({})

type Params = {
  xml: string
  url: string
  xmlURL?: string
}

export const parseString = async ({ xml, url, xmlURL }: Params) => {
  return parser.parseString
    .bind(parser)(xml)
    .catch((e) => getToptal(url))
}

const getToptal = async (url: string) => {
  const { title, items } = await fetch(
    `https://www.toptal.com/developers/feed2json/convert?url=${url}`,
  ).then<R>((r) => r.json())

  return {
    title,
    items: items.map(({ title, url }) => ({
      title,
      link: url,
    })),
  }
}

// Generated by https://quicktype.io

export interface R {
  version: string
  title: string
  home_page_url: string
  items: Item[]
}

export interface Item {
  guid: string
  url: string
  title: string
  content_html: string
  date_published: string
  author: Author
}

export interface Author {
  name: string
}
