import Parser from 'rss-parser'

const parser = new Parser({})

type Params = {
  xml: string
  url: string
  xmlURL?: string
}

export const parseString = async ({ xml, url, xmlURL }: Params) => {
  return parser.parseString
    .bind(parser)(xml)
    .catch((e) => rssToJson(url))
}

const rssToJson = async (url: string) => {
  const {
    feed: { title },
    items,
  } = await fetch(
    `https://api.rss2json.com/v1/api.json?rss_url=${url}`,
  ).then<R>((r) => r.json())

  return {
    title,
    items: items.map(({ title, link }) => ({
      title,
      link,
    })),
  }
}

// Generated by https://quicktype.io

export interface R {
  status: string
  feed: Feed
  items: Item[]
}

export interface Feed {
  url: string
  title: string
  link: string
  author: string
  description: string
  image: string
}

export interface Item {
  title: string
  pubDate: string
  link: string
  guid: string
  author: string
  thumbnail: string
  description: string
  content: string
  enclosure: Enclosure
  categories: any[]
}

export interface Enclosure {
  thumbnail: string
}
// const getToptal = async (url: string) => {
//   const { title, items } = await fetch(
//     `https://www.toptal.com/developers/feed2json/convert?url=${url}`,
//   ).then<R>((r) => r.json())

//   return {
//     title,
//     items: items.map(({ title, url }) => ({
//       title,
//       link: url,
//     })),
//   }
// }
