export const sendDiscordMessage = (
  webhookURL: string,
  message: string | object,
): Promise<Response> => {
  return fetch(`${webhookURL}?${new URLSearchParams({ wait: 'true' })}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(
      typeof message === 'string' ? { content: message } : message,
    ),
  })
    .then<Response>((r) => r.json())
    .catch((e) => {
      console.error('Failed to send Discord message', message)
      return sendDiscordMessage(webhookURL, message)
    })
}

// Generated by https://quicktype.io

interface Response {
  id: string
  type: number
  content: string
  channel_id: string
  author: Author
  attachments: any[]
  embeds: any[]
  mentions: any[]
  mention_roles: any[]
  pinned: boolean
  mention_everyone: boolean
  tts: boolean
  timestamp: string
  edited_timestamp: null
  flags: number
  components: any[]
  webhook_id: string
}

interface Author {
  id: string
  username: string
  avatar: null
  discriminator: string
  public_flags: number
  flags: number
  bot: boolean
}
