import { env } from 'utils/secrets'

export const archive = async (url: string) => {
  return Promise.all([
    fetch('https://chrome-api.archive.org/save', {
      method: 'POST',
      headers: {
        accept: 'text/html,application/xhtml+xml,application/xml',
        'content-type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        'capture_all': '1',
        url
      }),
    })
      .then<R>((r) => r.json())
      .catch((e) => {
        console.error('Error archiving: ', url)
        console.error(e)
      }),
    fetch(`https://api.github.com/repos/howrs/archive/dispatches`, {
      method: 'POST',
      headers: {
        accept: 'application/vnd.github.v3+json',
        authorization: `token ${env().GITHUB_PAT_2}`,
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        event_type: 'archive',
        client_payload: {
          url: url.replace(/https?:\/\//, ''),
        },
      }),
    })
      .then<R>((r) => r.json())
      .catch((e) => {
        console.error('Error archiving: ', url)
        console.error(e)
      }),
  ])
}

// Generated by https://quicktype.io

export interface R {
  url: string
  job_id: string
  message?: string
}
